language: ruby

git:
  depth: 1

rvm:
  - 2.0.0
  - 2.1
  - ruby-head

services:
  - redis-server

sudo: false

bundler_args: --jobs=3 --retry=3 --deployment --local --without development

before_install:
  - sh -c "if [ '$RUBYGEMS_VERSION' != 'latest' ]; then gem update --system $RUBYGEMS_VERSION; fi"
  - gem --version

before_script:
  - cp config/database.yml.example config/database.yml
  - bundle exec rake db:create db:migrate db:test:prepare

env:
  - RUBYGEMS_VERSION=2.2.2
  - RUBYGEMS_VERSION=latest

matrix:
  allow_failures:
    - rvm: 2.1
    - rvm: ruby-head
